### ISSUE TITLE
Can not reproduce the result in Table 2.

### ISSUE THREAD

**Issue by TheSunWillRise** [facebookresearch/label_dp_antipodes#2]
Hellow.
I try to reproduce the results in Table. Specifically, to reproduce the result of $\epsilon=8$, I run 

`python train_cifar_alibi.py --dataset cifar100 --arch resnet --lr 0.0037 --weight-decay 0.00335  --sigma 0.35`

but only obtain 51% test accuracy.
Is there something wrong with my configuration?

**Comment by karthikprasad** [comment]
@815961618 ,
I have corrected my answer to your question on #1. Sorry for the back and forth.

**Comment by karthikprasad** [comment]
Closing this issue for now. Please feel free to reopen if the above comment did not address your issue.
