### ISSUE TITLE
cannot import name 'stats' from 'opacus.utils'

### ISSUE THREAD

**Issue by llbbcc** [facebookresearch/label_dp_antipodes#3]
Hi! When I run `python train_cifar_alibi.py`. I got an error 

```
ImportError: cannot import name 'stats' from 'opacus.utils'
```
My `opcaus` version is 1.1.1.

**Comment by karthikprasad** [comment]
Hello @llbbcc, thanks for your interest. Opacus API changed since v1.0.0, and we haven't updated this library since then.
In the meantime, you can use opacus v0.15.0
