### ISSUE TITLE
Inappropriate picture dimension

### ISSUE THREAD

**Issue by zk375142817** [facebookresearch/label_dp_antipodes#5]
How to solve it：
RuntimeError: The size of tensor a (32) must match the size of tensor b (3) at non-singleton dimension 2

**Comment by karthikprasad** [comment]
Hi @zk375142817 , can you share a colab notebook with your code that produces this error?

**Comment by zk375142817** [comment]
Thank you for your reply. I did the experiment on pychar. He prompted me about the error I commented on. Then I tried colab and found that it didn't work. This is my experiment link:https://colab.research.google.com/drive/1YztWhGQJB3b_JiSAbKfireTqUalsSWRy?usp=sharing,thank you again




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/label_dp_antipodes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 上午9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/label_dp_antipodes] Inappropriate picture dimension (Issue #5)





 
Hi @zk375142817 , can you share a colab notebook with your code that produces this error?

**Comment by karthikprasad** [comment]
Hi @zk375142817 , I don't see the error `RuntimeError: The size of tensor a (32) must match the size of tensor b (3) at non-singleton dimension 2` spit out anywhere in your colab. Did you perhaps share the wrong notebook?

**Comment by karthikprasad** [comment]
Closing as there has been no follow-up. Please feel free to reopen if the issue persists.
